---
- name: Run Shell Commands
  hosts: all
  gather_facts: false
  tasks:
    - name: run command # noqa
      shell: "{{ shell_command }}"
      register: shell_output

    - name: Display shell command output
      debug:
        var: shell_output.stdout_lines
