---
- name: Check for existing gluster volume.
  command: gluster volume info "{{ gluster_volume_name }}"
  register: gluster_volume_info
  ignore_errors: true

- name: Verify gluster volume brick directory
  file:
    path: "{{ gluster_volume_path }}/brick"
    state: directory

- name: Configure gluster volume.
  gluster_volume:
    state: present
    name: "{{ gluster_volume_name }}"
    brick: "{{ gluster_volume_path}}/brick"
    replicas: 3
    cluster: "{{ groups['swarm'] | map('extract', hostvars, 'ansible_default_ipv4.address') | join(',') }}"
    host: "{{ ansible_default_ipv4.interface }}"
    force: yes
  run_once: true
  when: gluster_volume_info.rc !=0
  
