---
- name: Create gluster volume path.
  file:
    path: "{{ gluster_volume_path }}"
    state: directory

- name: Make xfs filesystem on gluster data device.
  filesystem:
    fstype: xfs
    dev: "{{ gluster_data_device }}"

- name: Mount gluster volume path to gluster data device.
  mount:
    path: "{{ gluster_volume_path }}"
    src: "{{ gluster_data_device }}"
    fstype: xfs
    state: mounted
