---
- name: Install gluster and dependencies.
  apt:
    pkg:
      - xfsprogs
      - attr
      - glusterfs-server
      - glusterfs-common
      - glusterfs-client
    state: present
    force_apt_get: true

- name: Enable gluster service.
  systemd:
    name: glusterd
    enabled: true
