---
- name: Install keepalived
  package:
    name: keepalived
    state: present
    enabled: true

- name: initialize priority fact.
  set_fact:
    keepalived_priority: "{{ 100 - (10 * (play_hosts.index(inventory_hostname))) }}"
  when: keepalived_priority is not defined

- name: configure keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: restart keepalived
