---
# make sure the base requirements are met.
#- import_playbook: ../deploy-new-server/main.yml

- name: "k3s raspberry pi cluster"
  hosts: k3s
  become: true
  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: update apt cache
      become: true
      apt:
        update_cache: true
        cache_valid_time: 3600

  roles:
    - ../../roles/k3s

  tasks:
    - debug:
        msg: "This playbook is for k3s_cluster"
