---
# this playbook builds out a basic folder structure for ansible playbooks

- name: prompt for project details
  hosts: localhost

  vars_prompt:
    - name: project_name
      prompt: "create a project name"
      private: no

    - name: project_description
      prompt: "give a short project description. (Like deploy new postgres server)"
      private: no

  tasks:
    - name: create project directories.
      file:
        path: "../playbooks/{{ project_name }}/{{ item }}"
        state: directory
      delegate_to: localhost
      loop:
        - vars
        - tasks

    - name: create a readme file.
      copy:
        dest: "../playbooks/{{ project_name }}/README.md"
        content: |
          # {{ project_name }}
          ## {{ project_description }}
      delegate_to: localhost

    - name: create main.yml in the project root.
      copy:
        dest: "../playbooks/{{ project_name }}/main.yml"
        content: |
          --- 
          # make sure the base requirements are met. 
          - import_playbook: ../deploy-new-server/main.yml

          - name: "{{ project_description }}"
            hosts:
            vars_files:
              - vars/main.yml
            
            pre_tasks:
              - name: update apt cache
                become: true
                apt:
                  update_cache: true
                  cache_valid_time: 3600
            
            # roles:
            #   - role-name-here 

            tasks:
              - debug:
                  msg: "This playbook is for {{ project_name}}"
      delegate_to: localhost

    - name: create vars main.yml.
      copy:
        dest: "../playbooks/{{ project_name }}/vars/main.yml"
        content: |
          ---
          # empty vars file
      delegate_to: localhost

    - name: symlink ansible configuration file
      file:
        src: "../../ansible.cfg"
        dest: "../playbooks/{{ project_name }}/ansible.cfg"
        state: link
