---
# make sure the base requirements are met.
- import_playbook: ../deploy-new-server/main.yml

- name: "Deploys docker swarm clusters and adds nodes to existing swarm clusters"
  hosts: swarm
  become: true
  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: update apt cache
      become: true
      apt:
        update_cache: true
        cache_valid_time: 3600

  roles:
    - ../../docker

  tasks:
    - debug:
        msg: "This playbook is for deploy-pi-swarm-nodes"
